/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.3.3.0 (NJsonSchema v9.4.2.0) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming


export class TechCompleteSuggestionListDto implements ITechCompleteSuggestionListDto {
    id: number;
    displayName?: string | undefined;
    isVisible: boolean;
    isDeleted: boolean;

    constructor(data?: ITechCompleteSuggestionListDto) {
        // super(data);
    }

    init(data?: any) {
        // super.init(data);
        if (data) {
            this.id = data["Id"];
            this.displayName = data["DisplayName"];
            this.isVisible = data["IsVisible"];
            this.isDeleted = data["IsDeleted"];
        }
    }

    static fromJS(data: any): TechCompleteSuggestionListDto {
        let result = new TechCompleteSuggestionListDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["DisplayName"] = this.displayName;
        data["IsVisible"] = this.isVisible;
        data["IsDeleted"] = this.isDeleted;
        // super.toJSON(data);
        return data; 
    }
}

export interface ITechCompleteSuggestionListDto {
    id: number;
    displayName?: string | undefined;
    isVisible: boolean;
    isDeleted: boolean;
}

function throwException(message: string, status: number, response: string, result?: any): any {
    if(result !== null && result !== undefined)
        throw result;
}